data_path: "/glade/scratch/dgagne/track_data_ncarstorm_3km_REFL_COM_ws_nc/"
patch_radius: 16
input_variables: ["REFL_COM_curr", "U10_curr", "V10_curr"]
output_variables: ["UP_HELI_MAX_curr"]
meta_variables: ["masks", "i", "j", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
train_start_date: "2010-10-01"
train_end_date: "2014-12-31"
val_start_date: "2014-01-01"
val_end_date: "2014-12-31"
test_start_date: "2015-01-01"
test_end_date: "2017-06-30"
out_path: "/glade/work/cbecker/HWT_mode/charlie/charlie_mode_cnn_uh_20200504/"
classifier: 1
classifier_threshold: 50
plot_kwargs:
  REFL_COM_curr:
    vmin: 0
    vmax: 80
    cmap: "gist_ncar"

models:
  cnn_20200504_000:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 1.5
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "max"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 0
    dropout_alpha: 0.2
    epochs: 30
    dense_neurons: 4
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
